name: Deploying NodeJS Code
on: workflow_dispatch
jobs:
    FirstJob:
        runs-on: ubuntu-latest
        steps:
            - name: Get Repo Code
              uses: actions/checkout@v4

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with: 
                node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Run Lint
              run: npm run lint

            - name: Build NodeJs
              run: npm run build
              
            - name: Test NodeJS
              run: npm run test
              
            - name: Deploying Code
              run: echo "Code Deployed Successfully!"  



            
              
            


              
